language: go
go:
  - 1.15.7
env: "PATH=/home/travis/gopath/bin:$PATH"

script:
  - go vet -x ./...

  # Build linux/amd64 archive
  - export GOOS="linux"
  - export GOARCH="amd64"
  - go build -v -tags "forceposix" -o build/linux-x64/cli-kintone
  - zip linux-x64.zip build/linux-x64/cli-kintone

  # Build darwin/amd64 archive
  - export GOOS="darwin"
  - export GOARCH="amd64"
  - go build -v -tags "forceposix" -o build/macos-x64/cli-kintone
  - zip macos-x64.zip build/macos-x64/cli-kintone

  # Build windows/amd64 archive
  - export GOOS="windows"
  - export GOARCH="amd64"
  - go build -v -tags "forceposix" -o build/windows-x64/cli-kintone.exe
  - zip windows-x64.zip build/windows-x64/cli-kintone.exe

deploy:
  provider: releases
  api_key:
    secure: "R1+CD3pjU5mYnOAS78fBKdLs4ZvrRszU3kYSW6vUgCwFLRLV2XlcOl7KNLuLGZSrOIid0UWzGalHYmdiRWOew15C1GaUsT4IcmD//ACII/0E9r3yCd2iPs6Nv0Xk0ynfFqO1HFwXf1HqMSElZEevfpGdnLtpirhpBMFX6vxHZiAMhVzkPH02U24R25qjJfsKF98l9dLv1/wjG556UYuKXFnKhF8nYWFeqBPrY17Q7NSufJ3F7c9O8OpY8xlqFp8yG55dogI2bh+aCLap+7EzU/GVn4l07Ug1z//VK7lAMO/OZI507UfW4zvLbza3LPM5ie9ggN+8qzqohm40HDuuNSiUdefrWoOTNpRFLwFtQWHLkSQnqK5a6qmC+mhy6ztBvflLtm8ARahus7oDTYlcvy2LV7E1yWZ3TtTFHrg9NI3pKe2Jru1O7udfoGPtqLYvw+BkWLdDRnWn0d5GOEsrfuq2u4k7iPI8tePjbemSGuyZ7OCr0JFq6wK4huCeU+/Ha4qABe81c0vTUQj8oJ6Ut56Ca82q5smb+DRE4Z98MUkEyU34f6heitzwQJu+IHA8+NbgA3a+vme0zvhl4IHhfGAxYRFdDnn7M4QuPN9NL3GNcxr9d6JTkN6N4m2hOK0i+SGVQ0x3v4SFCwqPQdg3FAtDkNbQnyAbJY13xlcO19Y="
  file:
    - "linux-x64.zip"
    - "macos-x64.zip"
    - "windows-x64.zip"
  cleanup: false
  on:
    tags: true
    all_branches: true  # https://github.com/travis-ci/travis-ci/issues/1675
